// This file is automatically generated, do not edit manually
#include "Arduino.h"
const uint32_t mtMajor = 0;
const uint32_t mtMinor = 1;
const uint32_t mtPatch = 0;
const String mtSuffix = " ";
const String mtVersion = "0.1.0";
